from __future__ import annotations

import argparse
import copy
import json
import math
import os
import time
import urllib.request
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageEnhance, ImageFilter, ImageOps


PUBLIC_BASE_URL = "https://u6oaq5xqg2yrxzlq.public.blob.vercel-storage.com"


def load_env(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key, value.strip().strip('"'))


def request_json(url: str, api_key: str, payload: dict | None = None) -> dict:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        url,
        data=data,
        method="POST" if payload is not None else "GET",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        return json.loads(response.read().decode("utf-8"))


def download(url: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as response:
        output.write_bytes(response.read())


def adjust_light(recipe: dict, token: str, scale: float) -> None:
    for item in recipe.get("source_scene", {}).get("light_adjustments", []):
        if token in item.get("contains", []):
            item["power_scale"] = scale


def adjust_card(recipe: dict, token: str, value: float, strength: float) -> None:
    for item in recipe.get("source_scene", {}).get("object_adjustments", []):
        if token not in item.get("contains", []):
            continue
        adjust = item.setdefault("source_material_adjust", {})
        color = [value, value, value + 0.003, 1.0]
        adjust["base_color"] = color
        adjust["diffuse_color"] = color
        adjust["emission_color"] = color
        adjust["emission_strength_scale"] = strength


def make_preview_candidates(base: dict, prefix: str, resolution: int, samples: int) -> list[dict]:
    variants = [
        {
            "suffix": "base",
            "front": 0.98,
            "fill": 0.46,
            "top": 0.62,
            "sparkle": 1.92,
            "dark": 0.012,
            "dark_strength": 0.54,
            "gray": 0.36,
            "symmetry_strength": 0.62,
            "symmetry_contrast": 1.32,
            "symmetry_brightness": 0.98,
            "symmetry_cutoff": 0.30,
        },
        {
            "suffix": "balanced_fill",
            "front": 0.88,
            "fill": 0.62,
            "top": 0.54,
            "sparkle": 2.08,
            "dark": 0.010,
            "dark_strength": 0.62,
            "gray": 0.28,
            "symmetry_strength": 0.68,
            "symmetry_contrast": 1.34,
            "symmetry_brightness": 0.975,
            "symmetry_cutoff": 0.34,
        },
        {
            "suffix": "facet_contrast",
            "front": 0.82,
            "fill": 0.58,
            "top": 0.50,
            "sparkle": 2.22,
            "dark": 0.008,
            "dark_strength": 0.68,
            "gray": 0.24,
            "symmetry_strength": 0.74,
            "symmetry_contrast": 1.42,
            "symmetry_brightness": 0.965,
            "symmetry_cutoff": 0.40,
        },
        {
            "suffix": "clean_bright",
            "front": 0.94,
            "fill": 0.56,
            "top": 0.66,
            "sparkle": 2.00,
            "dark": 0.014,
            "dark_strength": 0.56,
            "gray": 0.34,
            "symmetry_strength": 0.56,
            "symmetry_contrast": 1.24,
            "symmetry_brightness": 0.998,
            "symmetry_cutoff": 0.24,
        },
        {
            "suffix": "shadow_safe",
            "front": 0.90,
            "fill": 0.54,
            "top": 0.58,
            "sparkle": 1.98,
            "dark": 0.011,
            "dark_strength": 0.58,
            "gray": 0.32,
            "symmetry_strength": 0.64,
            "symmetry_contrast": 1.30,
            "symmetry_brightness": 0.985,
            "symmetry_cutoff": 0.30,
        },
    ]

    recipes = []
    for variant in variants:
        recipe = copy.deepcopy(base)
        recipe["name"] = f"{prefix}_{variant['suffix']}_preview"
        recipe["description"] = "Low-resolution preview candidate generated by preview_refine_render.py."
        recipe.setdefault("render", {})
        recipe["render"]["resolution"] = [resolution, resolution]
        recipe["render"]["samples"] = samples
        recipe["render"]["denoise"] = True
        adjust_light(recipe, "large_front_left_softbox", variant["front"])
        adjust_light(recipe, "weak_front_right_fill", variant["fill"])
        adjust_light(recipe, "low_top_softbox", variant["top"])
        adjust_light(recipe, "diamond_micro_sparkle", variant["sparkle"])
        adjust_card(recipe, "NEWS_FINAL_diamond_dark_facet_card", variant["dark"], variant["dark_strength"])
        adjust_card(recipe, "MASTER_SCENE_soft_gray_side_reflection", variant["gray"], 0.84)
        symmetry = recipe.setdefault("postprocess", {}).setdefault("center_stone_symmetry", {})
        symmetry.update(
            {
                "enabled": True,
                "object_contains": ["Diamond_Round_11"],
                "fallback_bounds_norm": [0.33, 0.22, 0.67, 0.58],
                "padding_px": 24,
                "target_side": "auto",
                "strength": variant["symmetry_strength"],
                "max_strength": min(0.82, variant["symmetry_strength"] + 0.08),
                "adaptive_strength": True,
                "contrast": variant["symmetry_contrast"],
                "brightness": variant["symmetry_brightness"],
                "saturation": 0.89,
                "sharpness": 1.22,
                "autocontrast_cutoff": variant["symmetry_cutoff"],
                "unsharp_radius": 0.9,
                "unsharp_percent": 105,
                "unsharp_threshold": 1,
                "mask_feather": 10,
                "split_feather": 12,
                "min_clarity_delta": 0.0,
                "min_mean_delta": 0.0,
            }
        )
        recipes.append(recipe)
    return recipes


def object_bounds(metadata: dict, image_size: tuple[int, int], tokens: list[str], fallback: list[float]) -> tuple[int, int, int, int]:
    lowered = [token.lower() for token in tokens]
    metadata_size = None
    recipe_resolution = metadata.get("recipe", {}).get("render", {}).get("resolution") if isinstance(metadata, dict) else None
    if isinstance(recipe_resolution, list) and len(recipe_resolution) == 2:
        try:
            metadata_size = (max(1, int(recipe_resolution[0])), max(1, int(recipe_resolution[1])))
        except (TypeError, ValueError):
            metadata_size = None
    for item in metadata.get("object_image_bounds", []):
        signature = str(item.get("signature") or item.get("name") or "").lower()
        bounds = item.get("bounds_px")
        if any(token in signature for token in lowered) and isinstance(bounds, list) and len(bounds) == 4:
            left, top, right, bottom = [int(value) for value in bounds]
            if metadata_size and metadata_size != image_size:
                sx = image_size[0] / metadata_size[0]
                sy = image_size[1] / metadata_size[1]
                return (int(left * sx), int(top * sy), int(right * sx), int(bottom * sy))
            return (left, top, right, bottom)
    width, height = image_size
    left, top, right, bottom = fallback
    return (int(left * width), int(top * height), int(right * width), int(bottom * height))


def ellipse_half_mask(size: tuple[int, int], side: str) -> Image.Image:
    width, height = size
    ellipse = Image.new("L", size, 0)
    draw = ImageDraw.Draw(ellipse)
    pad_x = int(width * 0.04)
    pad_y = int(height * 0.04)
    draw.ellipse((pad_x, pad_y, width - pad_x, height - pad_y), fill=255)
    half = Image.new("L", size, 0)
    draw = ImageDraw.Draw(half)
    if side == "left":
        draw.rectangle((0, 0, width // 2 + int(width * 0.08), height), fill=255)
    else:
        draw.rectangle((width // 2 - int(width * 0.08), 0, width, height), fill=255)
    return ImageChops.multiply(ellipse, half).filter(ImageFilter.GaussianBlur(4))


def masked_stats(image: Image.Image, mask: Image.Image) -> dict:
    gray = image.convert("L")
    edges = gray.filter(ImageFilter.FIND_EDGES)
    gray_values = list(gray.getdata())
    edge_values = list(edges.getdata())
    mask_values = list(mask.getdata())
    values = [value for value, alpha in zip(gray_values, mask_values) if alpha > 24]
    edge_sample = [value for value, alpha in zip(edge_values, mask_values) if alpha > 24]
    if not values:
        return {"mean": 0.0, "std": 0.0, "edge": 0.0, "clarity": 0.0}
    mean = sum(values) / len(values)
    variance = sum((value - mean) ** 2 for value in values) / len(values)
    std = variance ** 0.5
    edge = sum(edge_sample) / max(1, len(edge_sample))
    clarity = std + edge * 0.35 - max(0.0, mean - 154.0) * 0.12
    return {"mean": mean, "std": std, "edge": edge, "clarity": clarity}


def score_preview(image_path: Path, metadata: dict, recipe: dict) -> dict:
    with Image.open(image_path) as source:
        image = source.convert("RGB")
    bounds = object_bounds(
        metadata,
        image.size,
        ["diamond_round_11"],
        recipe.get("postprocess", {}).get("center_stone", {}).get("fallback_bounds_norm", [0.33, 0.22, 0.67, 0.58]),
    )
    left, top, right, bottom = bounds
    pad = max(6, int((right - left) * 0.12))
    left = max(0, left - pad)
    top = max(0, top - pad)
    right = min(image.width, right + pad)
    bottom = min(image.height, bottom + pad)
    crop = image.crop((left, top, right, bottom))
    left_stats = masked_stats(crop, ellipse_half_mask(crop.size, "left"))
    right_stats = masked_stats(crop, ellipse_half_mask(crop.size, "right"))
    symmetry = abs(left_stats["clarity"] - right_stats["clarity"])
    brightness_penalty = abs(((left_stats["mean"] + right_stats["mean"]) * 0.5) - 176.0) * 0.12
    clarity = (left_stats["clarity"] + right_stats["clarity"]) * 0.5
    score = clarity - symmetry * 2.2 - brightness_penalty
    return {
        "score": score,
        "symmetry_delta": symmetry,
        "left": left_stats,
        "right": right_stats,
        "brightness_penalty": brightness_penalty,
    }


def projected_final_look(image_path: Path, output_path: Path, resolution: int) -> Path:
    with Image.open(image_path) as source:
        image = source.convert("RGB")

    image = ImageOps.contain(image, (resolution, resolution), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (resolution, resolution), "white")
    canvas.paste(image, ((resolution - image.width) // 2, (resolution - image.height) // 2))

    # Preview renders are noisier and flatter than final renders. This projection applies
    # the expected final-grade direction so selection is based on the likely final look.
    projected = ImageEnhance.Contrast(canvas).enhance(1.08)
    projected = ImageEnhance.Brightness(projected).enhance(0.992)
    projected = ImageEnhance.Color(projected).enhance(0.96)
    projected = ImageEnhance.Sharpness(projected).enhance(1.10)
    projected = projected.filter(ImageFilter.UnsharpMask(radius=0.8, percent=70, threshold=2))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    projected.save(output_path, quality=96)
    return output_path


def submit_jobs(recipes: list[dict], parsed: argparse.Namespace, api_key: str, endpoint_id: str, phase: str) -> list[dict]:
    jobs = []
    for recipe in recipes:
        name = recipe["name"]
        output_prefix = f"{parsed.output_root.rstrip('/')}/{name}"
        payload = {
            "input": {
                "job_id": name,
                "model": {"url": parsed.model_url, "pathname": parsed.model_pathname},
                "recipe": recipe,
                "output": {"prefix": output_prefix},
            }
        }
        submitted = request_json(f"https://api.runpod.ai/v2/{endpoint_id}/run", api_key, payload)
        runpod_job_id = submitted.get("id") or submitted.get("jobId")
        if not runpod_job_id:
            raise SystemExit(json.dumps(submitted, indent=2))
        jobs.append({"name": name, "runpod_job_id": runpod_job_id, "output_prefix": output_prefix, "recipe": recipe})
        print(json.dumps({"phase": phase, "submitted": name, "runpod_job_id": runpod_job_id}))
    return jobs


def wait_and_download(jobs: list[dict], parsed: argparse.Namespace, api_key: str, endpoint_id: str, timeout_seconds: int) -> list[dict]:
    pending = {job["name"]: job for job in jobs}
    completed: dict[str, dict] = {}
    deadline = time.time() + timeout_seconds
    while pending and time.time() < deadline:
        time.sleep(8)
        for name, job in list(pending.items()):
            status = request_json(f"https://api.runpod.ai/v2/{endpoint_id}/status/{job['runpod_job_id']}", api_key)
            state = status.get("status")
            print(json.dumps({"name": name, "status": state}))
            if state == "COMPLETED":
                completed[name] = status.get("output", {})
                del pending[name]
            elif state in {"FAILED", "CANCELLED", "TIMED_OUT"}:
                raise SystemExit(json.dumps({"name": name, "status": status}, indent=2))

    if pending:
        raise SystemExit(json.dumps({"error": "Timed out waiting for jobs.", "pending": sorted(pending)}, indent=2))

    results = []
    for job in jobs:
        name = job["name"]
        output = completed[name]
        image_url = output.get("image_url") or f"{PUBLIC_BASE_URL}/{job['output_prefix']}/{name}.png"
        metadata_url = output.get("metadata_blob", {}).get("url") or f"{PUBLIC_BASE_URL}/{job['output_prefix']}/{name}.json"
        image_path = Path(parsed.output_root) / f"{name}.png"
        metadata_path = Path(parsed.output_root) / f"{name}.metadata.json"
        download(image_url, image_path)
        try:
            download(metadata_url, metadata_path)
            metadata = json.loads(metadata_path.read_text(encoding="utf-8-sig"))
        except Exception:
            metadata = {}
        results.append({"job": job, "image_url": image_url, "metadata_url": metadata_url, "image_path": image_path, "metadata": metadata})
        print(json.dumps({"name": name, "image_url": image_url, "metadata_url": metadata_url}))
    return results


def make_contact_sheet(results: list[dict], output: Path, tile_size: int, image_key: str = "image_path") -> None:
    cols = min(3, max(1, len(results)))
    rows = math.ceil(len(results) / cols)
    label_h = 42
    sheet = Image.new("RGB", (cols * tile_size, rows * (tile_size + label_h)), "white")
    draw = ImageDraw.Draw(sheet)
    for index, result in enumerate(results):
        col = index % cols
        row = index // cols
        x = col * tile_size
        y = row * (tile_size + label_h)
        with Image.open(result[image_key]) as img:
            tile = img.convert("RGB")
            tile.thumbnail((tile_size, tile_size))
            sheet.paste(tile, (x + (tile_size - tile.width) // 2, y + label_h + (tile_size - tile.height) // 2))
        score = result.get("score", {})
        label = f"{result['job']['name']} score={score.get('score', 0):.1f} sym={score.get('symmetry_delta', 0):.1f}"
        draw.text((x + 8, y + 6), label[:70], fill=(0, 0, 0))
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)


def args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render cheap previews, score them, and optionally render the best final.")
    parser.add_argument("--base-recipe", required=True)
    parser.add_argument("--prefix", default="preview_refine")
    parser.add_argument("--model-url", default="https://u6oaq5xqg2yrxzlq.public.blob.vercel-storage.com/models/son2.blend")
    parser.add_argument("--model-pathname", default="models/son2.blend")
    parser.add_argument("--endpoint-id", default="")
    parser.add_argument("--output-root", default="outputs/ring99")
    parser.add_argument("--preview-resolution", type=int, default=560)
    parser.add_argument("--preview-samples", type=int, default=140)
    parser.add_argument("--final-resolution", type=int, default=1200)
    parser.add_argument("--final-samples", type=int, default=860)
    parser.add_argument("--projection-resolution", type=int, default=1200)
    parser.add_argument("--timeout-seconds", type=int, default=1800)
    parser.add_argument("--render-final", action="store_true")
    return parser.parse_args()


def main() -> None:
    parsed = args()
    load_env(Path(".env"))
    api_key = os.environ.get("RUNPOD_API_KEY")
    endpoint_id = parsed.endpoint_id or os.environ.get("RUNPOD_ENDPOINT_ID", "4lvi3w848rqy0l")
    if not api_key:
        raise SystemExit("RUNPOD_API_KEY is missing.")

    base = json.loads(Path(parsed.base_recipe).read_text(encoding="utf-8-sig"))
    recipe_dir = Path(parsed.output_root) / "recipes"
    recipe_dir.mkdir(parents=True, exist_ok=True)
    previews = make_preview_candidates(base, parsed.prefix, parsed.preview_resolution, parsed.preview_samples)
    preview_paths = []
    for recipe in previews:
        path = recipe_dir / f"{recipe['name']}.json"
        path.write_text(json.dumps(recipe, indent=2), encoding="utf-8")
        preview_paths.append(path)

    jobs = submit_jobs(previews, parsed, api_key, endpoint_id, "preview")
    results = wait_and_download(jobs, parsed, api_key, endpoint_id, parsed.timeout_seconds)
    for result in results:
        projection_path = Path(parsed.output_root) / f"{result['job']['name']}.projection.png"
        result["projection_path"] = projected_final_look(result["image_path"], projection_path, parsed.projection_resolution)
        result["preview_score"] = score_preview(result["image_path"], result["metadata"], result["job"]["recipe"])
        result["score"] = score_preview(result["projection_path"], result["metadata"], result["job"]["recipe"])
        print(
            json.dumps(
                {
                    "preview": result["job"]["name"],
                    "preview_score": result["preview_score"],
                    "projection_score": result["score"],
                    "projection_path": str(result["projection_path"]),
                },
                indent=2,
            )
        )

    results.sort(key=lambda item: item["score"]["score"], reverse=True)
    contact_sheet = Path(parsed.output_root) / f"{parsed.prefix}_preview_contact_sheet.jpg"
    make_contact_sheet(results, contact_sheet, 380)
    projection_contact_sheet = Path(parsed.output_root) / f"{parsed.prefix}_projection_contact_sheet.jpg"
    make_contact_sheet(results, projection_contact_sheet, 380, image_key="projection_path")
    best = results[0]
    print(
        json.dumps(
            {
                "best_projection": best["job"]["name"],
                "score": best["score"],
                "preview_contact_sheet": str(contact_sheet),
                "projection_contact_sheet": str(projection_contact_sheet),
            },
            indent=2,
        )
    )

    final_recipe = copy.deepcopy(best["job"]["recipe"])
    final_recipe["name"] = f"{parsed.prefix}_final_from_{best['job']['name']}"
    final_recipe["description"] = f"Final high-quality render selected by preview_refine_render.py from preview {best['job']['name']}."
    final_recipe["render"]["resolution"] = [parsed.final_resolution, parsed.final_resolution]
    final_recipe["render"]["samples"] = parsed.final_samples
    final_path = recipe_dir / f"{final_recipe['name']}.json"
    final_path.write_text(json.dumps(final_recipe, indent=2), encoding="utf-8")
    print(json.dumps({"final_recipe": str(final_path)}))

    if parsed.render_final:
        final_jobs = submit_jobs([final_recipe], parsed, api_key, endpoint_id, "final")
        final_results = wait_and_download(final_jobs, parsed, api_key, endpoint_id, parsed.timeout_seconds)
        print(json.dumps({"final_image_url": final_results[0]["image_url"], "final_image_path": str(final_results[0]["image_path"])}, indent=2))


if __name__ == "__main__":
    main()
